// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_lab;

namespace Web_lab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Web_lab.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCustomer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdExecuter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CurrentOrder");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0c1355d-44cc-4554-a4b1-da63e831c35b"),
                            IdCustomer = new Guid("3b62472e-4f66-49fa-a20f-e7685b9565d8"),
                            IdExecuter = new Guid("00000000-0000-0000-0000-000000000000"),
                            Price = 500,
                            Status = 0,
                            Topic = "Сочинение"
                        });
                });

            modelBuilder.Entity("Web_lab.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NunberOrders")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b62472e-4f66-49fa-a20f-e7685b9565d8"),
                            Name = "Вася",
                            NunberOrders = 0,
                            Surname = "Белов",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("6f72f4dd-2243-4851-af60-dc393a203e27"),
                            Name = "Петя",
                            NunberOrders = 1,
                            Surname = "Петров",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
